### ISSUE TITLE
Nodepool custom_data Issues After https://github.com/sassoftware/viya4-iac-aws/pull/122

### ISSUE THREAD

**Issue by shealym** [sassoftware/viya4-iac-aws#153] opened 2022-08-04 12:46 UTC
### Terraform Version Details

{
  "terraform_version": "\"1.0.4\"",
  "terraform_revision": "null",
  "terraform_outdated": "false",
  "provider_selections": "{}"
}

...using the Docker-container

### Terraform Variable File Details

I'm having issues getting custom_data to populate in the Launch Templates or execute on the underlying AWS nodes using terraform.tfvars lines such as this:

`    "custom_data" = "./files/custom-data/additional_userdata.sh"`

or this:

`    "custom_data" = "/workspace/files/custom-data/additional_userdata.sh" (for the Docker container)`

from examples/sample-input-custom-data.tfvars.  

### Steps to Reproduce

Use the "custom_data" option to populate User Data in Launch Templates and run init-scripts on the AWS nodes.

### Expected Behavior

Init-scripts based on custom_data in the terraform.tfvars are part of the Launch Templates, and executed on the AWS nodes.

### Actual Behavior

User_Data is not created in the Launch Template based on custom_data contents in the terraform.tfvars.

### Additional Context

I know this has worked in the past, but it's been a number of months since I've needed to use it.  The custom_data simply doesn't show up under User Data in the Launch Template in AWS, and "user_data" doesn't show up as a line in a "terraform plan" execution under a section such as:

`       # module.eks.module.eks_managed_node_group["compute"].aws_launch_template.this[0] will be created`

Looking here, with the switch from additional_userdata to post_bootstrap_user_data in https://github.com/sassoftware/viya4-iac-aws/pull/122, it seems like "enable_bootstrap_user_data" needs to be set to true:

https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/submodules/_user_data#input_enable_bootstrap_user_data

...so I added that to the locals.tf under user_node_pool:

`        enable_bootstrap_user_data       = true`
`        post_bootstrap_user_data        = (np_value.custom_data != "" ? file(np_value.custom_data) : "")`

...which brought user_data as a line in the terraform plan for the launch template:

`     + user_data              = (known after apply)`

...but that errored out on a terraform apply with:

`│ Error: error waiting for EKS Node Group (viya4-poc-eks:compute-20220804032322452400000018) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 1 error occurred:
│       * : Ec2LaunchTemplateInvalidConfiguration: User data was not in the MIME multipart format.
│
│
│
│   with module.eks.module.eks_managed_node_group["compute"].aws_eks_node_group.this[0],
│   on .terraform/modules/eks/modules/eks-managed-node-group/[main.tf](http://main.tf/) line 269, in resource "aws_eks_node_group" "this":
│  269: resource "aws_eks_node_group" "this" {`

So I changed the additional_userdata.sh script to MIME multipart format using the "Amazon Linux user data" template here:

https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-user-data

...and then the code ends up in the Launch Template, and executes correctly on the node. 

I'm wondering if the sample-input-custom-data.tfvars works as-is after https://github.com/sassoftware/viya4-iac-aws/pull/122 on your side, or if the updates above need to be integrated into viya4-iac-aws?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by canpmh** [comment] 2022-08-09 15:56
This is identified at this Issue https://github.com/sassoftware/viya4-iac-aws/issues/139#issuecomment-1181123593 already.

There I provide one simple workaround:  this simple addition to locals.tf (around line 104, before post_bootstrap_user_data does seem to fix the issue:

pre_bootstrap_user_data = (np_value.custom_data != "" ? file(np_value.custom_data) : "")

**Comment by jarpat** [comment] 2022-09-15 20:13
Closing, this is a dupe of issue https://github.com/sassoftware/viya4-iac-aws/issues/139
PR #158 should resolve this.

**Closed by jarpat** 2022-09-15 20:13 UTC
Labels: bug, new
